<br \>
<br \>
<div class="logo">
    <a href="home.php">PARKR
    </a>
</div>
<!-- unordered list for nav, styled in css file -->
<ul class="nav">
    <li>
        <a href="home.php">home
        </a>
    </li>
    <li>
        <a href="search.php">search
        </a>
    </li>
    <li>
        <a href="submission.php">submit
        </a>
    </li>
    <li>
        <a href="register.php">register
        </a>
    </li>
    <li>
        <a href="login.php">login
        </a>
    </li>
    <li>
        <a href="logout.php">logout
        </a>
    </li>
    <br \>
    <br \>